from .augmentations import (
    BaseTransform,
    RandomNoiseAdder,
    PowerlineNoise,
    BaselineWander,
    EMGNoise,
    HighPassFilter,
    LowPassFilter,
    Scaling,
    RandomAmplitudeVariation,
    ClippingDistortion,
    SignalInverter,
    SignalDrift,
    SinusoidalStretching,
    EchoAdder,
    SignalArtefactAdder,
    ZeroOutSignal,
    ZeroOutChannel,
    SegmentShuffle,
    RandomSignalReplacement,
    SignalTimeStretch,
    DelaySimulation,
    RandomTimeShift,
    SignalCrop,
)

__version__ = "1.0.0"

__all__ = [
    "BaseTransform",
    "RandomNoiseAdder",
    "PowerlineNoise",
    "BaselineWander",
    "EMGNoise",
    "HighPassFilter",
    "LowPassFilter",
    "Scaling",
    "RandomAmplitudeVariation",
    "ClippingDistortion",
    "SignalInverter",
    "SignalDrift",
    "SinusoidalStretching",
    "EchoAdder",
    "SignalArtefactAdder",
    "ZeroOutSignal",
    "ZeroOutChannel",
    "SegmentShuffle",
    "RandomSignalReplacement",
    "SignalTimeStretch",
    "DelaySimulation",
    "RandomTimeShift",
    "SignalCrop",
]
